### ISSUE TITLE
parse errors using the shutter-icons

### ISSUE THREAD

**Issue by Mariusthvdb** [g-kiss/Home-Assistant-custom-shutter-icons#5]
inspector Google Chrome:
```
Error: <path> attribute d: Unexpected end of attribute. Expected number, "… 15H16V17H8V15M8".
```

inspector Safari:

```
Error: Problem parsing d="M3 4H21V8H19V20... 12H16V14H8V12M8 15H16V17H8V15M8"
```

on any entity I use with the shutter-icons:

```
input_datetime:

  cover_dorm:
    name: Cover dorm
    icon: csi:shutter-2
    has_date: false
    has_time: true
```

or
```
    input_number.test_minute:
      package: Test
      icon: csi:shutter-2

    input_boolean.test:
      package: Test
      icon: csi:shutter-3
```
the icons do show correctly.

detail: shutter-4 does **not** show the error

please have a look? thanks!
